<a href="https://colab.research.google.com/github/omniaghazy/python-with-NTI/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 d arrray to one col or one row


In [19]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array.shape[0])     # عشان هي 1d

    #0 =1     1=5


def conversionFlag(data , flag ="ONE COLUMN"):
  if flag =="ONE COLUMN":
    oneCol = data.reshape((data.shape[0],1))
    return oneCol
  if flag =="ONE ROW":
    onerow = data.reshape((1,data.shape[0]))
    return onerow


print(conversionFlag(array, "ONE COLUMN"))
print(conversionFlag(array, "ONE ROW"))


5
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


### Question: Create a null vector of size 10

### Answer:

In [1]:
import numpy as np
nullVector = np.zeros(10)
print(nullVector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Question: Create a vector with values ranging from 10 to 49

### Answer:

In [2]:

vector = np.arange(10,50)
print(vector)
#

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Question: Reverse a vector (first element becomes last)

### Answer:

In [4]:
reverse = vector[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Question: Create a 3x3 matrix with values ranging from 0 to 8

### Answer:

In [5]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Question: Find indices of non-zero elements from [1,2,0,0,4,0]

### Answer:

In [8]:
array = np.array([1,2,0,0,4,0])

print(array[np.nonzero(array)])

[1 2 4]


### Question: Create a 10x10 array with random values and find the minimum, maximum and mean values

### Answer:

In [12]:

array = np.random.random(100).reshape(10,10)
print(array)
print(np.max(array))
print(np.min(array))
print(np.mean(array))

[[0.90699258 0.15539715 0.83491323 0.70158882 0.15201701 0.81599397
  0.16008261 0.14961193 0.6006496  0.95101433]
 [0.22391618 0.52906483 0.34995027 0.26158431 0.8926881  0.09646884
  0.18248996 0.26398934 0.60100592 0.77576903]
 [0.55476132 0.15702598 0.91896111 0.34755626 0.40200785 0.50622065
  0.09934141 0.91669219 0.60847264 0.69183116]
 [0.24943984 0.42418617 0.10675472 0.23561857 0.9010689  0.04204231
  0.37317897 0.73157665 0.0276408  0.90254054]
 [0.44364724 0.0903877  0.26700627 0.79979251 0.45217943 0.04642655
  0.18515315 0.06155381 0.81453475 0.97232184]
 [0.66920905 0.1928088  0.58971905 0.56641243 0.79208975 0.87804232
  0.20275669 0.79551064 0.02638321 0.43018905]
 [0.03062609 0.92224047 0.94788607 0.65713979 0.83952095 0.61837142
  0.45731334 0.19306664 0.1226799  0.45790455]
 [0.32545052 0.73521926 0.63774524 0.60782777 0.74804214 0.18885674
  0.77619848 0.99237705 0.23733564 0.97259187]
 [0.8073879  0.42425728 0.3110037  0.13863643 0.33739766 0.7424165
  0.21552936 

### Question: What is the result of the following expressions?
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

### Answer

In [14]:
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


### Question: Write a NumPy program to convert a list and tuple into arrays.
List to array:  [1 2 3 4 5 6 7 8]
    
Tuples to array:  ((8, 4), (6,1), (2, 3))
    
## Answer:

In [16]:
def convert2array(notarray):
    return np.array(notarray)



list = [1,2,3,4,5,6,7,8]
tuple = ((8,4),(6,1),(2,3))

print(convert2array(list))
print(convert2array(tuple))


[1 2 3 4 5 6 7 8]
[[8 4]
 [6 1]
 [2 3]]


### Question: Write a NumPy program to append values to the end of an array.
Original array:  [10, 20, 30]
After append values to the end of the array:  [10 20 30 40 50 60 70 80 90]

### Answer:

In [26]:


array = np.array([10,20,30])
list = [40,50,60,70,80,90]
print(np.append(array,list))



[10 20 30 40 50 60 70 80 90]


### Question: How to add a border (filled with 0's) around an existing array?

### Answer:

In [38]:
array = np.ones((3,3))
print(np.pad(array,1))



[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Question: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

### Answer:\

In [83]:

array = np.random.random((6,7,8))
index_1d = 100 -1  # 100th element

z = index_1d % 8

remaining_index = index_1d // 8

y = remaining_index % 7

x = remaining_index // 7

value =array[x,y,z]

print(f"The index of the 100th element is ({x},{y},{z}) and its value = {value}")

The index of the 100th element is (1,5,3) and its value = 0.814782135449848


In [84]:
### Question: Normalize a 5x5 random matrix

### Answer:

In [85]:

array = np.random.random((5,5))
print(array)

[[0.45332072 0.10328059 0.65798182 0.74387059 0.61883005]
 [0.29834793 0.8993275  0.30718743 0.09029728 0.38316089]
 [0.12219429 0.02060107 0.36910325 0.36095071 0.31891164]
 [0.68487381 0.44379275 0.74636739 0.00928741 0.6010694 ]
 [0.03355612 0.13387833 0.05197854 0.83848973 0.79153591]]


In [86]:

normalized_array = (array - np.min(array)) / (np.max(array) - np.min(array))
print(normalized_array)

[[0.49889136 0.10560555 0.7288373  0.82533718 0.68484852]
 [0.32477247 1.         0.33470405 0.09101823 0.42006364]
 [0.12685594 0.0127114  0.40426925 0.39510951 0.34787672]
 [0.75905166 0.48818625 0.82814245 0.         0.66489363]
 [0.02726698 0.13998348 0.0479654  0.93164604 0.87889131]]


### Question: Given a 1D array, negate all elements which are between 3 and 8, in place

### Answer:

In [92]:
array = np.arange(11)
print(array)
print(array[(array>3) & (array<8)] )

[ 0  1  2  3  4  5  6  7  8  9 10]
[4 5 6 7]


### Question: How to find common values between two arrays?

### Answer:

In [93]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([3,4,5,6,7])

print(np.intersect1d(array1,array2))

[3 4 5]


### Question: Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Array1: [ 0 10 20 40 60]

Array2: [0, 40]

Expected Output:[ True False False True False]

### Answer:

In [95]:
array1 = np.array([0,10,20,40,60])
array2 = np.array([0,40])
listbool =[]
for element in array1:
    if element in array2:
        listbool.append(True)
    else:
        listbool.append(False)
print(listbool)




[True, False, False, True, False]


### Question: How to get all the dates corresponding to the month of July 2016?

### Answer:


### Question: Extract the integer part of a random array using 5 different methods

### Answer:

In [116]:
array = np.random.random( (3,5))

for element in array:
    print(element.astype(int))

array.astype(int)
print(array)

print(np.abs(array))

print(array.round())






[0 0 0 0 0]
[0 0 0 0 0]
[0 0 0 0 0]
[[0.55690102 0.23622079 0.68221317 0.66036254 0.43959519]
 [0.00291944 0.89129781 0.29504339 0.69664242 0.81752208]
 [0.94222821 0.43429873 0.22451252 0.45346241 0.07787526]]
[[0.55690102 0.23622079 0.68221317 0.66036254 0.43959519]
 [0.00291944 0.89129781 0.29504339 0.69664242 0.81752208]
 [0.94222821 0.43429873 0.22451252 0.45346241 0.07787526]]
[[1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0.]]


### Question: Consider two random array A and B, check if they are equal

### Answer:

In [119]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5])
flag = np.array_equal(A,B)
print(flag)




True


### Question: How to find the closest value (to a given scalar) in a vector?

### Answer:

In [ ]:

vector = np.array([1,2,3,4,5])
sc