<a href="https://colab.research.google.com/github/omniaghazy/python-with-NTI/blob/main/lab2OmniaGhazy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The code problems sets in this excercise sheet are taken from many helpful resources.

Check them out for further practice:

https://www.kaggle.com/utsav15/100-numpy-exercises

https://www.w3resource.com/python-exercises/numpy/index.php
        
https://www.machinelearningplus.com/python/101-numpy-exercises-python/
    
https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/ ( *Multiple solutions per problem* )
    
https://favtutor.com/blogs/numpy-exercises-python

Level your coding skills by solving challenges: https://www.hackerrank.com/domains/python/numpy/difficulty/all/page/1

In [1]:
import numpy as np

### Question: Create a null vector of size 10

### Answer:

In [3]:
nullVector = np.zeros(10 ,"int")
print(nullVector)

[0 0 0 0 0 0 0 0 0 0]


### Question: Create a vector with values ranging from 10 to 49

### Answer:

In [6]:
vector = np.arange(10,50,1)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Question: Reverse a vector (first element becomes last)

### Answer:

In [7]:
reverse=vector[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### Question: Create a 3x3 matrix with values ranging from 0 to 8

### Answer:

In [8]:
matrix=np.arange(0,9,1).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Question: Find indices of non-zero elements from [1,2,0,0,4,0]

### Answer:

In [13]:
vector = np.array([1,2,0,0,4,0])
for i,v in enumerate(vector):
  if v!=0:
    print(i)

# another solution
nz_indices = np.nonzero(vector)
print(nz_indices)


0
1
4
(array([0, 1, 4]),)


### Question: Create a 10x10 array with random values and find the minimum, maximum and mean values

### Answer:

In [14]:
randomArray = np.random.random(size=(10,10))
print(randomArray)
print(randomArray.min())
print(randomArray.max())
print(randomArray.mean())

[[0.47862335 0.34885833 0.91623197 0.6348094  0.04235259 0.994894
  0.44833395 0.32254417 0.25165453 0.62011916]
 [0.52792449 0.53527255 0.24134307 0.11617582 0.89461074 0.7408676
  0.72967469 0.84527542 0.32773186 0.32608064]
 [0.74297085 0.78619215 0.21817444 0.20713849 0.05775769 0.84305061
  0.25564874 0.07283574 0.59334702 0.14797221]
 [0.89956986 0.90419932 0.70080781 0.46105087 0.40004    0.44699894
  0.07818866 0.73561329 0.40150723 0.08943873]
 [0.07434911 0.53153683 0.78942789 0.60090879 0.12622429 0.31171985
  0.62980945 0.54428459 0.83210784 0.91440339]
 [0.66142192 0.43866588 0.51195701 0.1264528  0.66105222 0.15600798
  0.85225317 0.811861   0.70858798 0.00759252]
 [0.35652243 0.12895098 0.84592411 0.6069324  0.11248676 0.43667417
  0.70488544 0.04635355 0.86389189 0.57828511]
 [0.27340339 0.88609795 0.33646388 0.05338686 0.87661969 0.11626835
  0.39058226 0.50268648 0.19671109 0.74055023]
 [0.12721072 0.16049285 0.01911831 0.03150048 0.42365984 0.40653029
  0.41103411 0.

### Question: What is the result of the following expressions?
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

### Answer

In [15]:
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Question: Write a NumPy program to convert a list and tuple into arrays.
List to array:  [1 2 3 4 5 6 7 8]
    
Tuples to array:  ((8, 4), (6,1), (2, 3))
    
## Answer:

In [17]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8]
tuple1 = ((8, 4), (6,1), (2, 3))
array1 = np.array(list1)
array2 = np.array(tuple1)
print(array1)
print(array2)

[1 2 3 4 5 6 7 8]
[[8 4]
 [6 1]
 [2 3]]


### Question: Write a NumPy program to append values to the end of an array.
Original array:  [10, 20, 30]
After append values to the end of the array:  [10 20 30 40 50 60 70 80 90]

### Answer:

In [18]:
original= np.array([10, 20, 30])
appended = np.append(original,[40,50,60,70,80,90])
print(appended)

[10 20 30 40 50 60 70 80 90]


### Question: How to add a border (filled with 0's) around an existing array?

### Answer:

In [24]:
existingArray = np.array([(1,2,3),(4,5,6)])
print(existingArray)
print(np.pad(existingArray, pad_width=2, mode='constant', constant_values=0))

[[1 2 3]
 [4 5 6]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


### Question: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

### Answer:

In [29]:

import numpy as np

array = np.random.random((6, 7, 8))

index = 100 - 1
z = index % 8

remaining_index = index // 8

y = remaining_index % 7

x = remaining_index // 7

print(f"The index (x,y,z) of the 100th element (0-indexed 99th) is: ({int(x)}, {int(y)}, {int(z)})")



The index (x,y,z) of the 100th element (0-indexed 99th) is: (1, 5, 3)


### Question: Normalize a 5x5 random matrix

### Answer:

In [32]:
randomArray = np.random.random((5,5))
normalized = (randomArray - np.min(randomArray)) / (np.max(randomArray) - np.min(randomArray))
print(normalized)

[[0.82851782 0.75321137 0.83807382 0.53317601 0.60888873]
 [0.22914765 0.41705379 0.60340097 0.7958949  0.38094718]
 [0.43057983 0.03774306 0.38739531 0.89242054 1.        ]
 [0.47543894 0.2843998  0.1076096  0.04958954 0.        ]
 [0.28277281 0.82701484 0.27470622 0.10094319 0.52498298]]


### Question: Given a 1D array, negate all elements which are between 3 and 8, in place

### Answer:

In [33]:
oneD=np.array([3,4,5,6,7,8,9,10,11,12,13,16])
oneD[(oneD>3) & (oneD<8)] *= -1
print(oneD)

[ 3 -4 -5 -6 -7  8  9 10 11 12 13 16]


### Question: How to find common values between two arrays?

### Answer:

In [34]:
array1=np.array([1,2,3,4,5,6])
array2=np.array([3,4,5,6,7,8])
print(np.intersect1d(array1,array2))

[3 4 5 6]


### Question: Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Array1: [ 0 10 20 40 60]

Array2: [0, 40]

Expected Output:[ True False False True False]

### Answer:

In [39]:
array1=np.array([ 0, 10 ,20, 40, 60])
array2=np.array([0, 40])
print(np.in1d(array1,array2))

#another sol
print(np.isin(array1,array2))

#another sol
L =[]
for i in array1:
  if i in array2:
    L.append(True)
  else:
    L.append(False)
print(L)



[ True False False  True False]
[ True False False  True False]
[True, False, False, True, False]


/tmp/ipython-input-39-961667488.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(array1,array2))


### Question: How to get all the dates corresponding to the month of July 2016?

### Answer:

In [41]:

dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### Question: Extract the integer part of a random array using 5 different methods

### Answer:

In [42]:


Z = np.random.uniform(-5, 5, 10)
print("Original array:", Z)

# Method 1
print("Method 1 (astype int):", Z.astype(int))

# Method 2
print("Method 2 (np.trunc()):", np.trunc(Z))

# Method 3
print("Method 3 (np.floor()):", np.floor(Z))

# Method 4 (getting integer part using np.ceil for negatives and np.floor for positives)
print("Method 4 (conditional floor/ceil):", np.where(Z >= 0, np.floor(Z), np.ceil(Z)))

# Method 5
print("Method 5 (np.modf()):", np.modf(Z)[1])

Original array: [-1.29150019 -1.13484223  1.32587331 -0.97441553 -2.95119284  1.88449378
  3.60085202 -3.91876423 -4.33666448  3.42700934]
Method 1 (astype int): [-1 -1  1  0 -2  1  3 -3 -4  3]
Method 2 (np.trunc()): [-1. -1.  1. -0. -2.  1.  3. -3. -4.  3.]
Method 3 (np.floor()): [-2. -2.  1. -1. -3.  1.  3. -4. -5.  3.]
Method 4 (conditional floor/ceil): [-1. -1.  1. -0. -2.  1.  3. -3. -4.  3.]
Method 5 (np.modf()): [-1. -1.  1. -0. -2.  1.  3. -3. -4.  3.]


### Question: Consider two random array A and B, check if they are equal

### Answer:

In [43]:

A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))
C = A.copy()

print("Array A:\n", A)
print("Array B:\n", B)
print("Array C:\n", C)

print("A and B are equal:", np.array_equal(A, B))
print("A and C are equal:", np.array_equal(A, C))

Array A:
 [[4 5 1]
 [3 9 6]
 [6 2 8]]
Array B:
 [[7 9 6]
 [0 2 8]
 [2 2 1]]
Array C:
 [[4 5 1]
 [3 9 6]
 [6 2 8]]
A and B are equal: False
A and C are equal: True


### Question: How to find the closest value (to a given scalar) in a vector?

### Answer:

In [44]:

Z = np.random.uniform(0, 10, 10)
scalar = 4.2

print("Vector:", Z)
print("Scalar:", scalar)

index = (np.abs(Z - scalar)).argmin()
closest_value = Z[index]

print("Closest value in the vector:", closest_value)

Vector: [2.48375445 4.62715053 3.91548428 5.06800474 1.37343259 1.85235175
 3.64926268 3.22863008 7.83452216 1.77363455]
Scalar: 4.2
Closest value in the vector: 3.915484283714077


### Question: Find the nearest value from a given value in an array

### Answer:

In [45]:

Z = np.random.uniform(0, 10, 10)
given_value = 7.5

print("Array:", Z)
print("Given value:", given_value)

index = np.abs(Z - given_value).argmin()
nearest_value = Z[index]

print("Nearest value in the array:", nearest_value)

Array: [7.79682737 9.01679556 0.72703054 0.53383914 2.53108631 7.67137066
 1.41512275 1.45026365 5.34587425 2.20424015]
Given value: 7.5
Nearest value in the array: 7.671370660188264


### Question: Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

### Answer:

In [46]:

Z = np.array([1, 12, 5, 20, 8, 15, 3])
print("Original array:", Z)

mask = Z > 10

values_greater_than_10 = Z[mask]

indices_greater_than_10 = np.where(mask)[0]

print("Values greater than 10:", values_greater_than_10)
print("Indices of elements greater than 10:", indices_greater_than_10)

Original array: [ 1 12  5 20  8 15  3]
Values greater than 10: [12 20 15]
Indices of elements greater than 10: [1 3 5]


### Question: Write a NumPy program to save a NumPy array to a text file.

### Answer:

In [50]:

array_to_save = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
file_name = "my_numpy_array.txt"

print("Array to save:\n", array_to_save)

np.savetxt(file_name, array_to_save)

print(f"Array saved to {file_name}")



Array to save:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array saved to my_numpy_array.txt


### Question: How to read the following file?

### Answer:

In [51]:
loaded_array = np.loadtxt(file_name)
print("Loaded array from file:\n", loaded_array)

Loaded array from file:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Question: What is the equivalent of enumerate for numpy arrays?

### Answer:

In [52]:

my_array = np.array([[10, 20, 30],
                     [40, 50, 60]])

for index, value in np.ndenumerate(my_array):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 10
Index: (0, 1), Value: 20
Index: (0, 2), Value: 30
Index: (1, 0), Value: 40
Index: (1, 1), Value: 50
Index: (1, 2), Value: 60


### Question: Subtract the mean of each row of a matrix

### Answer:

In [53]:


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)


row_means = np.mean(matrix, axis=1)
print("\nMean of each row:", row_means)

subtracted_matrix = matrix - row_means.reshape(-1, 1)

print("\nMatrix after subtracting mean of each row:\n", subtracted_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean of each row: [2. 5. 8.]

Matrix after subtracting mean of each row:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


### Question: How to sort an array by the nth column?

### Answer:

In [54]:
import numpy as np

my_array = np.array([[30, 10, 25],
                     [10, 50, 5],
                     [20, 30, 15],
                     [40, 20, 35]])

print("Original Array:\n", my_array)

n_column_index = 1

sorted_indices = my_array[:, n_column_index].argsort()

sorted_array = my_array[sorted_indices]

print(f"\nArray sorted by column {n_column_index}:\n", sorted_array)

Original Array:
 [[30 10 25]
 [10 50  5]
 [20 30 15]
 [40 20 35]]

Array sorted by column 1:
 [[30 10 25]
 [40 20 35]
 [20 30 15]
 [10 50  5]]


### Question: Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).
first_names = (‘Betsey’, ‘Shelley’, ‘Lanell’, ‘Genesis’, ‘Margery’)

last_names = (‘Battle’, ‘Brien’, ‘Plotner’, ‘Stahl’, ‘Woolum’)

### Answer:

In [55]:
import numpy as np

first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')

sorted_indices = np.lexsort((first_names, last_names))

print("Original first names:", first_names)
print("Original last names:", last_names)
print("Indices after sorting (first by last name, then by first name):", sorted_indices)

Original first names: ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
Original last names: ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')
Indices after sorting (first by last name, then by first name): [0 1 2 3 4]


### Question: How to tell if a given 2D array has null columns?

### Answer:

In [57]:
import numpy as np

array_with_zero_column = np.array([[1, 0, 3],
                                   [4, 0, 6],
                                   [7, 0, 9]])

array_with_nan_column = np.array([[1, np.nan, 3],
                                  [4, np.nan, 6],
                                  [7, np.nan, 9]])

print("Original Array (with zero column):\n", array_with_zero_column)
print("Are there any all-zero columns?", np.any(np.all(array_with_zero_column == 0, axis=0)))
print("Which columns are all-zero (mask):", np.all(array_with_zero_column == 0, axis=0))

print("\nOriginal Array (with NaN column):\n", array_with_nan_column)
print("Are there any all-NaN columns?", np.any(np.all(np.isnan(array_with_nan_column), axis=0)))
print("Which columns are all-NaN (mask):", np.all(np.isnan(array_with_nan_column), axis=0))

Original Array (with zero column):
 [[1 0 3]
 [4 0 6]
 [7 0 9]]
Are there any all-zero columns? True
Which columns are all-zero (mask): [False  True False]

Original Array (with NaN column):
 [[ 1. nan  3.]
 [ 4. nan  6.]
 [ 7. nan  9.]]
Are there any all-NaN columns? True
Which columns are all-NaN (mask): [False  True False]


### Question: Considering a four dimensions array, how to get sum over the last two axis at once?
happens in avgpooling [batch,channel,hight,width]

### Answer:

In [58]:
import numpy as np

my_4d_array = np.arange(2 * 3 * 4 * 5).reshape(2, 3, 4, 5)

print("Original Array Shape:", my_4d_array.shape)

summed_array = np.sum(my_4d_array, axis=(2, 3))

print("New Array Shape:", summed_array.shape)
print("Summed Array:\n", summed_array)

Original Array Shape: (2, 3, 4, 5)
New Array Shape: (2, 3)
Summed Array:
 [[ 190  590  990]
 [1390 1790 2190]]


### Related: Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
happens in avgpooling [batch,channel,hight,width]

### Answer:

In [59]:
import numpy as np

matrix = np.arange(16 * 16).reshape(16, 16)

print("Original Matrix Shape:", matrix.shape)

block_size = 4

reshaped_for_blocks = matrix.reshape(
    matrix.shape[0] // block_size, block_size,
    matrix.shape[1] // block_size, block_size
)

block_sum_matrix = reshaped_for_blocks.sum(axis=(1, 3))

print("Block-sum Matrix Shape:", block_sum_matrix.shape)
print("Block-sum Matrix:\n", block_sum_matrix)

Original Matrix Shape: (16, 16)
Block-sum Matrix Shape: (4, 4)
Block-sum Matrix:
 [[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


### Question: How to swap two rows of an array?

### Answer:

In [60]:

my_array = np.arange(9).reshape(3, 3)

print("Original Array:\n", my_array)

row1_to_swap = 0
row2_to_swap = 2

my_array[[row1_to_swap, row2_to_swap]] = my_array[[row2_to_swap, row1_to_swap]]

print("\nArray after swapping rows:\n", my_array)

Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Array after swapping rows:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


### Question: How to get the n largest values of an array
happens in one-to-many classifier (top n predictions)

### Answer:

In [61]:
import numpy as np

my_array = np.array([10, 2, 8, 15, 5, 20, 1, 12, 7])
n_largest = 3

print("Original Array:", my_array)


largest_values = my_array[np.argsort(my_array)[-n_largest:]]

print(f"The {n_largest} largest values are:", largest_values)

Original Array: [10  2  8 15  5 20  1 12  7]
The 3 largest values are: [12 15 20]


### Question: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
simulating sequential model training feed

### Answer:

In [62]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4

num_windows = len(Z) - window_size + 1

R = np.array([Z[i:i+window_size] for i in range(num_windows)])

print("Original Array Z:", Z)
print("Generated Array R:\n", R)
print("Shape of R:", R.shape)

Original Array Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Generated Array R:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
Shape of R: (11, 4)
